vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    product:
      uri_prefix: /uploads/products
      upload_destination: "%kernel.project_dir%/public/uploads/products"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false #default true, should the file be deleted when the entity is removed
      delete_on_update: true #default true, should the file be deleted when a new file is uploaded
      delete_on_remove: true #default false, should the file be injected into the uploadable entity when it is loaded from the data store. The object will be an instance of Symfony\Component\HttpFoundation\File\File

    user:
      uri_prefix: /uploads/users
      upload_destination: "%kernel.project_dir%/public/uploads/users"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false #default true, should the file be deleted when the entity is removed
      delete_on_update: true #default true, should the file be deleted when a new file is uploaded
      delete_on_remove: true #default false, should the file be injected into the uploadable entity when it is loaded from the data store. The object will be an instance of Symfony\Component\HttpFoundation\File\File

